# Generated by Django 3.1 on 2023-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeData',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=500, null=True)),
                ('product_desc', models.TextField(null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('rating', models.CharField(default=None, max_length=15, null=True)),
                ('image', models.TextField(default=None, null=True)),
                ('scraped_date', models.DateTimeField(auto_now_add=True, verbose_name='date_scraped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
